#cloud-config

write_files:
  - path: /etc/kubernetes/manifests/kube-scheduler.yaml
    permissions: 0600
    owner: root
    content: |
      apiVersion: v1
      kind: Pod
      metadata:
        name: kube-scheduler
        namespace: kube-system
      spec:
        hostNetwork: true
        containers:
        - name: kube-scheduler
          image: quay.io/coreos/hyperkube:$hyperkube_version
          command:
          - /hyperkube
          - scheduler
          - --master=http://127.0.0.1:8080
          - --leader-elect=true
          livenessProbe:
            httpGet:
              host: 127.0.0.1
              path: /healthz
              port: 10251
            initialDelaySeconds: 15
            timeoutSeconds: 1
  - path: /etc/kubernetes/manifests/kube-proxy.yaml
    permissions: 0600
    owner: root
    content: |
      apiVersion: v1
      kind: Pod
      metadata:
        name: kube-proxy
        namespace: kube-system
      spec:
        hostNetwork: true
        containers:
        - name: kube-proxy
          image: quay.io/coreos/hyperkube:$hyperkube_version
          command:
          - /hyperkube
          - proxy
          - --master=http://127.0.0.1:8080
          - --proxy-mode=iptables
          securityContext:
            privileged: true
          volumeMounts:
          - mountPath: /etc/ssl/certs
            name: ssl-certs-host
            readOnly: true
        volumes:
        - hostPath:
            path: /usr/share/ca-certificates
          name: ssl-certs-host
  - path: /etc/kubernetes/manifests/kube-controller-manager.yaml
    permissions: 0600
    owner: root
    content: |
      apiVersion: v1
      kind: Pod
      metadata:
        name: kube-controller-manager
        namespace: kube-system
      spec:
        hostNetwork: true
        containers:
        - name: kube-controller-manager
          image: quay.io/coreos/hyperkube:$hyperkube_version
          command:
          - /hyperkube
          - controller-manager
          - --master=http://127.0.0.1:8080
          - --leader-elect=true 
          - --service-account-private-key-file=/etc/kubernetes/ssl/apiserver-key.pem
          - --root-ca-file=/etc/kubernetes/ssl/ca.pem
          livenessProbe:
            httpGet:
              host: 127.0.0.1
              path: /healthz
              port: 10252
            initialDelaySeconds: 15
            timeoutSeconds: 1
          volumeMounts:
          - mountPath: /etc/kubernetes/ssl
            name: ssl-certs-kubernetes
            readOnly: true
          - mountPath: /etc/ssl/certs
            name: ssl-certs-host
            readOnly: true
        volumes:
        - hostPath:
            path: /etc/kubernetes/ssl
          name: ssl-certs-kubernetes
        - hostPath:
            path: /usr/share/ca-certificates
          name: ssl-certs-host
  - path: /etc/kubernetes/ssl/apiserver-key.pem
    permissions: 0600
    owner: root
    content: |
      -----BEGIN RSA PRIVATE KEY-----
      MIIEoQIBAAKCAQEAmBSauRkMEA+BnkAjBUpP2c9WbIr5CZmMzZ3E3pb4tnSTOD5b
      AvNVV2/x6MRmI1uaTnEiLMpKIvRFqMe9pY7zeZZKdP7FvkczfzoIcYnbexzVEpcv
      5TY25YX9dUNMKP7ulNRxyhJjGV14OLpHFqJAMdjaUXt8gCdHUI9jq83rhyZDUnDs
      cJwUz+sd8l2183wH6cc87EiPfhxk4IPbk/AEYefE1FGuLZ7FHcuwUZWWYNUXUKtx
      WQK2lTxjrDX8Bu5i9wu2fU21egChchqMlAr0hdOtWLCUDyUzHiowkZ7LzWTYQ/NW
      wVHhsDKu+y0h/454etuoORCCJBE5PcjevAHj4wIDAQABAoH/TKIVVTBJ483sgtHO
      09ueYSMZaZid5Th6uyHFEmUA7u/PP4gsVFBJsMW4IJLW5PpDx0M69Vb6BKMSdvov
      lj1yctJIsquu+TLnwDR+DLhq4J6mv7dvaxDmmMHr9irzNbVAg76JmEmrphxzeCJl
      sAISVwvu9yBCnFEunmmiz+/zvyXB6oggXfbROT9bpx5ckZy7NlY2dJhuM1zinSD7
      K6bBD5YuN5JN1OQgV0smyAR9Ubxsa/jTIZWz+WU2J6KyYPRzefpTAkCwhxniIeWW
      owF38o1PLcHmZyc8S6rYUO7L7tazjN8jBxGAYNhjmk6ueZ20dz20qxN2rxxqJo0z
      ziT5AoGBAMbFYwwgEruXicoUPPvleYnF+NEaqw4Xae6Txn3HFVu44Vgb8viIvbMP
      jpJesFJdVd3rXVYNFukItIsBxTZe+bB6PeKbFDILAtg4LuWcQ3dZIFpgcTUBcO6B
      PklaNWy83lq2zjizRO5vKt/uFiUEfk4i9bFleK/7zX2bYjlQvVy3AoGBAMPd2DXZ
      SXqVheD2+v4l4Ckno+dFGMVHWvlSqlNIn0YBprCVJCABw2L1l20uGFM4oXiWIfVi
      7CHF4sO6nrXAdgb2/dndHFg12zvdFeFxo48gwLS+kJRREkG83buXG8CSPcoswIdu
      4jnPOeIByQdVwmmvUsVk5PResK81UhnL0d41AoGAEFqNG6JH6Ec/fvDLU649oag4
      IHwhNreWb5qY6iBHEZTUdXtXMjuN3/2XrVM9Dom/VtLWiw3opKOitw0ePKrzwCFO
      liZMMxHU2hVFRn7kzhz3HHhy1/mWYQkhJsfVPW0MnkoMDX4yXauny2S7TbBg8+zM
      ahv/IfuFnJ/8JNsPuWECgYBp0NpUDTXDQjB33zauQywdT8se0JeXTPt7Iwvdvqg9
      m/q//3Lqz8kNF31dgL+nhjrF+OYTugO0I0JlV9cSfg3FqX5vSyNbDI2Kg+CkUU55
      rsotW56kYkAov65TAEn/+YHkTdUd1evmK2wsC6bdjZlgm1VuSxneY6G0pmvaf+C7
      2QKBgQC1LvfqL4WTjVDerFCOehGuMguh0UUwqOcGSfTxoG6rmchBPrP5QM9pcutE
      CQJd+89cJsD2uZ61iAXz+jRaaLolkeFRlzZzHcr8EgxsuV7KN/c5/8KnDu+rD/n7
      7xcjENZhvP6Vn+hkuqh/j8aF0gfP5SrLNfYWYCEraWHBBVa40A==
      -----END RSA PRIVATE KEY-----
  - path: /etc/kubernetes/ssl/apiserver.pem
    permissions: 0600
    owner: root
    content: |
      -----BEGIN CERTIFICATE-----
      MIIC8jCCAdqgAwIBAgIJAKTGdTVvDcE7MA0GCSqGSIb3DQEBBQUAMBIxEDAOBgNV
      BAMTB2t1YmUtY2EwHhcNMTYwNTI1MTkxNDMzWhcNMTcwNTI1MTkxNDMzWjAZMRcw
      FQYDVQQDDA5rdWJlLWFwaXNlcnZlcjCCASIwDQYJKoZIhvcNAQEBBQADggEPADCC
      AQoCggEBAJgUmrkZDBAPgZ5AIwVKT9nPVmyK+QmZjM2dxN6W+LZ0kzg+WwLzVVdv
      8ejEZiNbmk5xIizKSiL0RajHvaWO83mWSnT+xb5HM386CHGJ23sc1RKXL+U2NuWF
      /XVDTCj+7pTUccoSYxldeDi6RxaiQDHY2lF7fIAnR1CPY6vN64cmQ1Jw7HCcFM/r
      HfJdtfN8B+nHPOxIj34cZOCD25PwBGHnxNRRri2exR3LsFGVlmDVF1CrcVkCtpU8
      Y6w1/AbuYvcLtn1NtXoAoXIajJQK9IXTrViwlA8lMx4qMJGey81k2EPzVsFR4bAy
      rvstIf+OeHrbqDkQgiQROT3I3rwB4+MCAwEAAaNEMEIwCQYDVR0TBAIwADALBgNV
      HQ8EBAMCBeAwKAYDVR0RBCEwH4IRa3ViZXJuZXRlcy1tYXN0ZXKHBAoDAAGHBAoA
      AAIwDQYJKoZIhvcNAQEFBQADggEBAKb5qcC+v0CANP3WFGqJIr/fxztaucLqAmLA
      4eTLFD3PW7HN3vb8HW19GpoWLXYM4B83Luky5Pu4BEQuw5F7i+vSmxh6/dzsms75
      pi0knrS7UHjM3lhGBf6mW6DsafGdqmF41UgBMWKyemR1wVC2CeRYPkVnqpYmH77G
      2WKXBcefYNWnKnC9DFBbX17fpt2SZXuv+HRAmoIUpcHq/DsMXxs8xckbdYV7kc9W
      zMtsSM2hZZBYbkPBdIYLWgxNkKkKmFBl4zvwepstBvj4cM+DJEfKOhkjXuCvnO+i
      i3LxHKbPHKn5chYB+lA10hfEFr0z7vFjOGbRK9DN0lcK5rZ7+zA=
      -----END CERTIFICATE-----
  - path: /etc/kubernetes/manifests/kube-apiserver.yaml
    permissions: 0600
    owner: root
    content: |
      apiVersion: v1
      kind: Pod
      metadata:
        name: kube-apiserver
        namespace: kube-system
      spec:
        hostNetwork: true
        containers:
        - name: kube-apiserver
          image: quay.io/coreos/hyperkube:$hyperkube_version
          command:
          - /hyperkube
          - apiserver
          - --bind-address=0.0.0.0
          - --etcd-servers=$etcd_endpoints
          - --allow-privileged=true
          - --service-cluster-ip-range=10.254.254.0/24
          - --secure-port=443
          - --advertise-address=$advertise_ip
          - --admission-control=NamespaceLifecycle,NamespaceExists,LimitRanger,SecurityContextDeny,ServiceAccount,ResourceQuota
          - --tls-cert-file=/etc/kubernetes/ssl/apiserver.pem
          - --tls-private-key-file=/etc/kubernetes/ssl/apiserver-key.pem
          - --client-ca-file=/etc/kubernetes/ssl/ca.pem
          - --service-account-key-file=/etc/kubernetes/ssl/apiserver-key.pem
          - --runtime-config=extensions/v1beta1=true,extensions/v1beta1/thirdpartyresources=true
          ports:
          - containerPort: 443
            hostPort: 443
            name: https
          - containerPort: 8080
            hostPort: 8080
            name: local
          volumeMounts:
          - mountPath: /etc/kubernetes/ssl
            name: ssl-certs-kubernetes
            readOnly: true
          - mountPath: /etc/ssl/certs
            name: ssl-certs-host
            readOnly: true
        volumes:
        - hostPath:
            path: /etc/kubernetes/ssl
          name: ssl-certs-kubernetes
        - hostPath:
            path: /usr/share/ca-certificates
          name: ssl-certs-host
  - path: /etc/kubernetes/ssl/ca.pem
    permissions: 0600
    owner: root
    content: |
      -----BEGIN CERTIFICATE-----
      MIIDGjCCAgKgAwIBAgIJAIGuaQDbLIOBMA0GCSqGSIb3DQEBBQUAMBIxEDAOBgNV
      BAMTB2t1YmUtY2EwHhcNMTYwNTI1MTkxNDMzWhcNNDMxMDExMTkxNDMzWjASMRAw
      DgYDVQQDEwdrdWJlLWNhMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA
      x/oil7eFKzaoOMkeQ7s93EaydC/+EPkbdKD2Q3wtbkzdMo2o5oKajqsU/WuQQXoa
      /XzXPQl61ovSNnscDqzTQkB7X+OdTUOccE8gdsBzs2LIrq9QeidwAAzCkGpMnOzF
      CfhJ4e6kQGF4gZqNlB5xxh8nmp3AdPn2Z0GMDJWQh3F96kP152gX4UZAj/UkfNsi
      gRa/5zVgo03hC1SPF5UVbmYshrESwyPN0kpEHf77fmxz3agxUaQBrVVtBCgw/5Fr
      rUosjsOsddMIumUiQiqhuOv61MPCH3dDbG+jxwnfBrCLmxYkKijHyjoUnCiKMQ4y
      K6fCe4xe/Snsirw5wV8N2wIDAQABo3MwcTAdBgNVHQ4EFgQUwo/i4oaO0t3iKbQ2
      J15HhZO3DeYwQgYDVR0jBDswOYAUwo/i4oaO0t3iKbQ2J15HhZO3DeahFqQUMBIx
      EDAOBgNVBAMTB2t1YmUtY2GCCQCBrmkA2yyDgTAMBgNVHRMEBTADAQH/MA0GCSqG
      SIb3DQEBBQUAA4IBAQB2ZZMXpBVHbQYRM73srctK0/PuqglygnJX2VPtus8mFF+p
      mnJWN2R6JCXBAtv/dlDedZPZI9MlbfDqlHSM9jCNhW4TcFTEkcGxZaO1Of7tNop7
      hxhSsQJcwaEaaFVHr0/bf2ey7NBuEsHdvitH7Q4kUoNcCVViPlgovwKJ9lp4FPMi
      uO0J3ppaIpQNJx2IqkARv4aG5gFJJyQ+GfAkSVi6+xtDnodqScH8WIDjJEfgN7Np
      bS2tYX/uiyvfPoUBe9xdTGnvtTKzDq1FZxlFjE1iEY01ugbjTA0t2WLfAtn4DhIN
      /7xMPQmO9FWKtVgvmhd2otckpt2CPfdRsJbo9+gg
      -----END CERTIFICATE-----
  - path: /etc/environment-kubelet
    permissions: 0600
    owner: root
    content: |
      KUBELET_VERSION=$hyperkube_version
  - path: /etc/flannel/options.env
    permission: 0600
    owner: root
    content: |
      FLANNELD_IFACE=$advertise_ip
      FLANNELD_ETCD_ENDPOINTS=$etcd_endpoints

coreos:
  update:
    reboot-strategy: $reboot_strategy
  units:
    - name: flanneld.service
      drop-ins:
        - name: 40-ExecStartPre-symlink.conf
          content: |
            [Service]
            ExecStartPre=/usr/bin/ln -sf /etc/flannel/options.env /run/flannel/options.env
      command: start
    - name: docker.service
      drop-ins:
        - name: 40-flannel.conf
          content: |
            [Unit]
            Requires=flanneld.service
            After=flanneld.service
      command: start
    - name: kubelet.service
      content : |
        [Service]
        ExecStartPre=/usr/bin/mkdir -p /etc/kubernetes/manifests
        EnvironmentFile=/etc/environment
        EnvironmentFile=/etc/environment-kubelet
        ExecStart=/usr/lib/coreos/kubelet-wrapper \
          --api-servers=http://127.0.0.1:8080 \
          --network-plugin-dir=/etc/kubernetes/cni/net.d \
          --register-schedulable=false \
          --allow-privileged=true \
          --config=/etc/kubernetes/manifests \
          --hostname-override=${COREOS_PRIVATE_IPV4}
        Restart=always
        RestartSec=10
        [Install]
        WantedBy=multi-user.target 
      command: start
      enable: true
