heat_template_version: 2014-10-16

description: >
  kubernetes worker

parameters:
  network:
    type: string
    description: Network to connect to. NO default value.
  key_name:
    type: string
    description: Name of keypair to assign to servers
  etcd_endpoints:
    type: string
    description: Comma separated list of etcd server http://10.0.0.16:2379,
    default: http://10.0.0.10:2379,http://10.0.0.11:2379,http://10.0.0.12:2379,http://10.0.0.13:2379,http://10.0.0.14:2379
  hyperkube_version:
    type: string
    description: hyperkube version see https://quay.io/repository/coreos/hyperkube?tab=tags
  count:
    type: string
    description: Number of kubernetes workers, default 2
    default: 2
  image:
    type: string
    description: Name of image to use for servers
  flavor:
    type: string
    default: m1.micro
    description: Flavor to use for nodes
  coreos_reboot_strategy:
    type: string
    default: "etcd-lock"
    description: Enable or disable reboot for update (best-effort|etcd-lock|reboot|off). Default off.

resources:

  kubernetes_worker_security_group:
    type: OS::Neutron::SecurityGroup
    properties:
      description: allow access to kubernetes woker
      name:
        list_join:
          - '-'
          - - { get_param: 'OS::stack_name' }
            - kubernetes-worker
      rules:
        - remote_ip_prefix: 0.0.0.0/0
          protocol: tcp
          port_range_min: 22
          port_range_max: 22
        - remote_ip_prefix: 0.0.0.0/0
          protocol: icmp
        - remote_ip_prefix: 0.0.0.0/0
          protocol: tcp
          port_range_min: 443
          port_range_max: 443
        - remote_ip_prefix: 0.0.0.0/0
          protocol: tcp
          port_range_min: 30000
          port_range_max: 32767

  # just using a ResourceGroup to be able to "include" the file
  kubernetes_worker:
    type: OS::Heat::ResourceGroup
    properties:
      count: { get_param: count }
      resource_def:
        type: kubernetes/worker/node.yaml
        properties:
          server_name:
            list_join:
              - ''
              - - { get_param: 'OS::stack_name' }
                - "%index%"
          network: { get_param: network }
          image: { get_param: image }
          flavor: { get_param: flavor }
          key_name: { get_param: key_name }
          coreos_reboot_strategy: { get_param: coreos_reboot_strategy }
          etcd_endpoints: { get_param: etcd_endpoints }
          hyperkube_version: { get_param: hyperkube_version }
          security_groups:
            - default
            - { get_resource: kubernetes_worker_security_group }

outputs:
  servers:
    description: Resulted servers
    value: { get_attr: [kubernetes_worker, server] }
  ports:
    description: Resultes ports
    value: { get_attr: [kubernetes_worker, port] }
