heat_template_version: 2014-10-16

description: >
  kubernetes worker

parameters:
  network:
    type: string
    description: Network to connect to. NO default value.
  key_name:
    type: string
    description: Name of keypair to assign to servers
  etcd_endpoints:
    type: string
    description: Comma separated list of etcd server http://10.0.0.16:2389,
  hyperkube_version:
    type: string
    description: hyperkube version see https://quay.io/repository/coreos/hyperkube?tab=tags
  count:
    type: string
    description: Number of kubernetes workers, default 2
    default: 2
  image:
    type: string
    description: Name of image to use for servers
    default: CoreOS Stable
  flavor:
    type: string
    default: m1.micro
    description: Flavor to use for nodes
  coreos_reboot_strategy:
    type: string
    default: "off"
    description: Enable or disable reboot for update (best-effort|etcd-lock|reboot|off). Default off.

resources:

  # just using a ResourceGroup to be able to "include" the file
  kubernetes_worker:
    type: OS::Heat::ResourceGroup
    properties:
      count: { get_param: count }
      resource_def:
        type: kubernetes/worker/node.yaml
        properties:
          server_name:
            list_join:
              - '-'
              - - { get_param: 'OS::stack_name' }
                - kubernetes-worker%index%
          network: { get_param: network }
          image: { get_param: image }
          flavor: { get_param: flavor }
          key_name: { get_param: key_name }
          coreos_reboot_strategy: { get_param: coreos_reboot_strategy }
          etcd_endpoints: { get_param: etcd_endpoints }
          hyperkube_version: { get_param: hyperkube_version }

outputs:
  servers:
    description: Resulted servers
    value: { get_attr: [kubernetes_worker, value] }
