parameters:
  image: "CoreOS Stable 1235.9.0"
  public_net_id: 2562b515-55cd-4470-9e3c-3aff33be74e6
  etcd_flavor: std.S
  master_flavor: std.S
  worker_flavor: std.S
  hyperkube_version: "v1.5.2_coreos.2"
